# Build settings
permalink: /blog/:year/:title/
markdown: kramdown
highlighter: pygments
plugins: [jekyll-paginate-v2]

pagination:
  enabled: true
  per_page: 3
  permalink: "/page/:num/"

comments: true

source: source
destination: _site
sass:
  sass_dir: _sass
  style: compressed # expanded

# SEO settings
title: Mohan Dhanwani
description: "Digital Marketing Automation Expert from Jaipur, India"
keywords: "Digital Marketing Automation, Digital Marketing"
url: https://mohadhanwani.com
baseurl: "/mohan"

google_analytics: 
repo: http://github.com/nandomoreirame/end2end
disqus_shortname: ""
disqus_site_shortname: ""

# Author settings
author:
  name: Mohan Dhanwani
  job: Marketing Automation Freelancer
  bio: "I help Business Owners, and Marketing Professionals in creating Effective Marketing Automation Campaigns, Websites, and Implementing the tools, and much more."
  thumb: /images/author.jpg
  email: mohanlaldhanwani@gmail.com
  url: https://mohandhanwani.com/
  github: https://github.com/mohandhanwani
  twitter: https://twitter.com/tsubasa_mohan
  facebook: https://facebook.com/tsubasa.mohan
  linkedin: https://linkedin.com/in/mohanlaldhanwani

# navbar pages
navbar:
  - slug: about
    title: About
  - slug: icons
    title: Icons
  - slug: blog
    title: Blog

exclude: ["config.rb", "src", "Gemfile", "Gemfile.lock", "package.json","README.md", "Rakefile"]
